'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'

interface AssessmentResultsProps {
  analysis: string
  formData: Record<number, string>
  onClose: () => void
}

export default function AssessmentResults({
  analysis,
  formData,
  onClose,
}: AssessmentResultsProps) {
  const [isExporting, setIsExporting] = useState(false)

  // Parse the analysis into sections
  const parseAnalysis = (text: string) => {
    const sections: Record<string, string> = {}
    let currentSection = ''
    let currentContent: string[] = []

    const lines = text.split('\n')
    
    lines.forEach((line) => {
      const trimmedLine = line.trim()
      
      // Check for section headers
      if (trimmedLine.includes('Biological Age:')) {
        sections.biologicalAge = trimmedLine.replace('Biological Age:', '').trim()
      } else if (trimmedLine === 'BRIEF:') {
        if (currentSection) {
          sections[currentSection] = currentContent.join('\n').trim()
        }
        currentSection = 'brief'
        currentContent = []
      } else if (trimmedLine === 'GOOD THINGS:') {
        if (currentSection) {
          sections[currentSection] = currentContent.join('\n').trim()
        }
        currentSection = 'goodThings'
        currentContent = []
      } else if (trimmedLine === 'BAD THINGS:') {
        if (currentSection) {
          sections[currentSection] = currentContent.join('\n').trim()
        }
        currentSection = 'badThings'
        currentContent = []
      } else if (trimmedLine === 'STEPS RECOMMENDED:') {
        if (currentSection) {
          sections[currentSection] = currentContent.join('\n').trim()
        }
        currentSection = 'stepsRecommended'
        currentContent = []
      } else if (trimmedLine && currentSection) {
        currentContent.push(trimmedLine)
      }
    })
    
    // Add last section
    if (currentSection) {
      sections[currentSection] = currentContent.join('\n').trim()
    }

    return sections
  }

  const sections = parseAnalysis(analysis)

  const exportToPDF = async () => {
    setIsExporting(true)
    
    // Dynamic import to avoid SSR issues
    const { jsPDF } = await import('jspdf')
    
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    // Brand colors
    const zenyaCyan = '#00D1C7'
    const zenyaBlack = '#0C0C0D'
    const zenyaTeal = '#0F2F3A'

    // Header with branding
    doc.setFillColor(12, 12, 13) // zenya-black
    doc.rect(0, 0, 210, 40, 'F')
    
    // Logo/Title
    doc.setTextColor(0, 209, 199) // zenya-cyan
    doc.setFontSize(24)
    doc.setFont('helvetica', 'bold')
    doc.text('ZENYA LAB', 105, 20, { align: 'center' })
    
    doc.setTextColor(163, 255, 228) // zenya-mint
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('Lifestyle & Biological Age Assessment', 105, 30, { align: 'center' })

    // Contact details
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'www.zenyalab.com'
    const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'contact@zenyalab.com'
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(8)
    doc.text(`${siteUrl} | ${contactEmail}`, 105, 36, { align: 'center' })

    // Divider line
    doc.setDrawColor(0, 209, 199)
    doc.setLineWidth(0.5)
    doc.line(20, 45, 190, 45)

    // Content
    let yPosition = 55
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')

    // Split analysis into paragraphs and add to PDF
    const paragraphs = analysis.split('\n\n').filter(p => p.trim())
    
    paragraphs.forEach((paragraph, index) => {
      const lines = doc.splitTextToSize(paragraph.trim(), 170)
      
      // Check if we need a new page
      if (yPosition + lines.length * 6 > 270) {
        doc.addPage()
        yPosition = 20
      }

      // Add paragraph
      lines.forEach((line: string) => {
        doc.text(line, 20, yPosition)
        yPosition += 6
      })
      
      yPosition += 4 // Space between paragraphs
    })

    // Footer on each page
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(128, 128, 128)
      doc.text(
        `Page ${i} of ${pageCount} | Generated by Zenya Lab`,
        105,
        285,
        { align: 'center' }
      )
    }

    // Generate filename
    const name = formData[1] || 'Assessment'
    const filename = `Zenya_Lab_Assessment_${name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`

    // Save PDF
    doc.save(filename)
    setIsExporting(false)
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      {/* Success Header */}
      <div className="text-center mb-8">
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.2, type: 'spring', stiffness: 200 }}
          className="w-16 h-16 rounded-full bg-zenya-cyan flex items-center justify-center mx-auto mb-4"
        >
          <svg
            className="w-8 h-8 text-zenya-black"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={3}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </motion.div>
        <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">
          Your Assessment is Ready
        </h3>
        <p className="text-zenya-cyan/70">
          Personalized longevity insights based on your lifestyle profile
        </p>
      </div>

      {/* Analysis Content */}
      <div className="space-y-4 max-h-[500px] overflow-y-auto">
        {/* Biological Age - Prominent Display */}
        {sections.biologicalAge && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-gradient-to-r from-zenya-cyan/20 to-zenya-mint/20 rounded-xl p-6 border-2 border-zenya-cyan/30"
          >
            <div className="text-center">
              <p className="text-sm text-zenya-cyan/70 mb-2 uppercase tracking-wider">Biological Age</p>
              <p className="text-5xl font-bold text-zenya-cyan">{sections.biologicalAge}</p>
            </div>
          </motion.div>
        )}

        {/* Brief Section */}
        {sections.brief && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-zenya-teal/20 rounded-xl p-5 border border-zenya-cyan/20"
          >
            <h4 className="text-lg font-bold text-zenya-cyan mb-3 uppercase tracking-wide">Brief</h4>
            <p className="text-white/90 leading-relaxed whitespace-pre-line">
              {sections.brief.replace(/\*\*/g, '').replace(/\*/g, '')}
            </p>
          </motion.div>
        )}

        {/* Good Things Section */}
        {sections.goodThings && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="bg-green-500/10 rounded-xl p-5 border border-green-500/30"
          >
            <h4 className="text-lg font-bold text-green-400 mb-3 uppercase tracking-wide">Good Things</h4>
            <ul className="space-y-2">
              {sections.goodThings
                .split('\n')
                .filter(line => line.trim() && (line.trim().startsWith('-') || line.trim().startsWith('•')))
                .map((item, index) => (
                  <li key={index} className="text-white/90 flex items-start">
                    <span className="text-green-400 mr-2">✓</span>
                    <span>{item.replace(/^[-•]\s*/, '').replace(/\*\*/g, '').replace(/\*/g, '')}</span>
                  </li>
                ))}
            </ul>
          </motion.div>
        )}

        {/* Bad Things Section */}
        {sections.badThings && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="bg-red-500/10 rounded-xl p-5 border border-red-500/30"
          >
            <h4 className="text-lg font-bold text-red-400 mb-3 uppercase tracking-wide">Bad Things</h4>
            <ul className="space-y-2">
              {sections.badThings
                .split('\n')
                .filter(line => line.trim() && (line.trim().startsWith('-') || line.trim().startsWith('•')))
                .map((item, index) => (
                  <li key={index} className="text-white/90 flex items-start">
                    <span className="text-red-400 mr-2">⚠</span>
                    <span>{item.replace(/^[-•]\s*/, '').replace(/\*\*/g, '').replace(/\*/g, '')}</span>
                  </li>
                ))}
            </ul>
          </motion.div>
        )}

        {/* Steps Recommended Section */}
        {sections.stepsRecommended && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="bg-zenya-teal/20 rounded-xl p-5 border border-zenya-cyan/20"
          >
            <h4 className="text-lg font-bold text-zenya-cyan mb-3 uppercase tracking-wide">Steps Recommended</h4>
            <ol className="space-y-3 list-decimal list-inside">
              {sections.stepsRecommended
                .split('\n')
                .filter(line => line.trim() && /^\d+\./.test(line.trim()))
                .map((item, index) => (
                  <li key={index} className="text-white/90 leading-relaxed">
                    {item.replace(/^\d+\.\s*/, '').replace(/\*\*/g, '').replace(/\*/g, '')}
                  </li>
                ))}
            </ol>
          </motion.div>
        )}

        {/* Fallback: If parsing fails, show raw content */}
        {!sections.brief && !sections.goodThings && (
          <div className="bg-zenya-teal/20 rounded-xl p-6 border border-zenya-cyan/20">
            <div className="prose prose-invert max-w-none">
              {analysis.split('\n\n').map((paragraph, index) => (
                <p
                  key={index}
                  className="text-white/90 mb-4 leading-relaxed whitespace-pre-line"
                  dangerouslySetInnerHTML={{
                    __html: paragraph
                      .trim()
                      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                      .replace(/\*(.*?)\*/g, '<em>$1</em>'),
                  }}
                />
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center">
        <button
          onClick={exportToPDF}
          disabled={isExporting}
          className="px-8 py-3 bg-zenya-cyan text-zenya-black font-semibold rounded-xl hover:glow-mint disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 flex items-center justify-center gap-2"
        >
          {isExporting ? (
            <>
              <svg className="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              Generating PDF...
            </>
          ) : (
            <>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Export as PDF
            </>
          )}
        </button>

        <button
          onClick={onClose}
          className="px-8 py-3 bg-zenya-teal/30 text-white border border-zenya-cyan/20 font-semibold rounded-xl hover:border-zenya-mint transition-all duration-300"
        >
          Close
        </button>
      </div>
    </motion.div>
  )
}

